package cz.vsb.ekf.lan0116.combat;

public enum Attacks {
    BACKSTAB,//DOUBLE DMG
    BLEED,//DMG APPLIED TWICE, SECOND TIME REDUCED BY HALF
    BLIND,//WEAKEN RANGED ATTACK
    CRUSHING_BLOW,//ATTACK TWICE, NOT IN SINGLE HIT, BUT TWICE, SO DEFENSE MORE EFFICIENT
    FEAR,//RESTRICTS ATTACK FOR ONE "LAP"
    HIT,
    INITIATIVE,
    LIFESTEAL,//DRAIN HALF OF HP TAKEN FROM TARGET
    MAGIC_BOLT,
    POISON,//DEALS DMG PERIODICALLY
    SCREAM,//REDUCES ALL ENEMY'S STATS BY 1
    SHOOT,//FIRST ATTACK TWICE
    SILENCE,//WEAKEN MAGIC ATTACK
    WEAKEN,//WEAKEN PHYSICAL ATTACK
    ;
}
