package cz.vsb.ekf.lan0116.combat;

public enum Attacks {
INITIATIVE,
HIT,
SCREAM,//REDUCES ALL ENEMY'S STATS BY 1
SHOOT,//FIRST ATTACK TWICE
BACKSTAB,//DOUBLE DMG
LIFESTEAL,//DRAIN HALF OF HP TAKEN FROM TARGET
BLEED,//DMG APPLIED TWICE, SECOND TIME REDUCED BY HALF
CRUSHING_BLOW,//ATTACK TWICE, NOT IN SINGLE HIT, BUT TWICE, SO DEFENSE MORE EFFICIENT 
MAGIC_BOLT,
BLIND,//WEAKEN RANGED ATTACK
SILENCE,//WEAKEN MAGIC ATTACK
WEAKEN,//WEAKEN PHYSICAL ATTACK   
POISON,//DEALS DMG PERIODICALLY
FEAR,//RESTRICTS ATTACK FOR ONE "LAP"
}
